### ISSUE TITLE
Handle malformed installimage config

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#18]
It is a normal use case that an administrator modifies the installimage config for a specific node (for example /srv/tftp/installimage/00_00_00_00), admins can be dump and break the layout, for example:

```
SCRIPT /usr/local/bin/start_installimage

SCRIPT /usrlocalbinstart_installimage
LABEL openbsd
IP_ADDRESS 10.3.7.41
LABEL openbsd
IP_ADDRESS 10.3.7.41
```

(this happens easily when you press wrong buttons in vim)

the API currently breaks if she tries to read this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3.5/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/marmoset/marmoset/webserver/installimage.py", line 29, in post
    installimage_config = InstallimageConfig(mac)
  File "/opt/marmoset/marmoset/installimage/installimage_config.py", line 21, in __init__
    self.__read_config_file()
  File "/opt/marmoset/marmoset/installimage/installimage_config.py", line 65, in __read_config_file
    value = line.split(" ", 1)[1].rstrip('\n')
IndexError: list index out of range
```

would it be possible to throw a suitable HTTP error code instead?

**Comment by bastelfreak** [comment]
config:

```
VAR3 qwe

VAR1 penis
VAR2 penis
``

results in:

```

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3.5/site-packages/flask_restful/**init**.py", line 270, in error_router
    return original_handler(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(_args, *_kwargs)
  File "/usr/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(_args, *_kwargs)
  File "/usr/lib/python3.5/site-packages/flask_restful/**init**.py", line 581, in dispatch_request
    resp = meth(_args, *_kwargs)
  File "/opt/marmoset/marmoset/webserver/pxe.py", line 39, in get
    re = pxe.ClientConfig(ip_address)
  File "/opt/marmoset/marmoset/pxe/client_config.py", line 53, in **init**
    if self.exists():
  File "/opt/marmoset/marmoset/pxe/client_config.py", line 65, in exists
    return os.path.isfile(self.file_path())
  File "/opt/marmoset/marmoset/pxe/client_config.py", line 124, in file_path
    name = self.file_name()
  File "/opt/marmoset/marmoset/pxe/client_config.py", line 118, in file_name
    return "%02X%02X%02X%02X" % tuple(octets)
ValueError: invalid literal for int() with base 10: '00:00:00:00'

```
```

**Comment by bastelfreak** [comment]
and with the correct endpoint:

```
root@dhcp01 /opt/marmoset # curl -u admin:secret http://localhost:8080/v1/pxe/00:00:00:00/config
{
  "message": "Route not found.",
  "status": 404
}
root@dhcp01 /opt/marmoset # git pull
Already up-to-date.
root@dhcp01 /opt/marmoset # cat /srv/tftp/installimage/00_00_00_00 
VAR3 qwe

VAR1 penis
VAR2 penis
root@dhcp01 /opt/marmoset #
```

**Comment by sebastianrakel** [comment]
i think this is fixed?

**Comment by bastelfreak** [comment]
fixed
