### ISSUE TITLE
GET /installimage/<mac> fails if no config is present

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/marmoset#20]
there is no config:

```
root@dhcp01 /opt/marmoset # cat /srv/tftp/installimage/00_00_00_00 
cat: /srv/tftp/installimage/00_00_00_00: No such file or directory
root@dhcp01 /opt/marmoset # curl -u admin:secret  http://localhost:8080/v1/installimage/00:00:00:00
```

which results in:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3.5/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.5/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/marmoset/marmoset/webserver/installimage.py", line 24, in get
    abort(404)
NameError: name 'abort' is not defined
```

**Comment by bastelfreak** [comment]
this is indeed fixed:

```
root@dhcp01 /opt/marmoset # curl -u admin:secret http://localhost:8080/v1/installimage/00:00:00:10
{
    "message": "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again. You have requested this URI [/v1/installimage/00:00:00:10] but did you mean /v1/installimage/<mac> or /v1/installimage or /v1/installimage/<mac>/config ?"
}
```
