### ISSUE TITLE
Getting DHCP entries does not work when upper case letters are used in the MAC address 

### ISSUE THREAD

**Issue by ghost** [virtapi/marmoset#56]
The DHCP endpoint does accept MAC addresses with upper case letters and saves them into the LDAP database. However once one entry with upper case letters (e.g. 08:00:27:2B:0B:36) exists in the database, it is no longer possible to get a listing of the existing DHCP entries via GET, Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.4/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/marmoset/marmoset/webserver/dhcp.py", line 27, in get
    return [vars(c) for c in dhcp.DhcpConfig.all()]
  File "/opt/marmoset/marmoset/dhcp/dhcp_config.py", line 64, in all
    return ISCDhcpLdapConfig.all()
  File "/opt/marmoset/marmoset/dhcp/isc_dhcp_ldap_config.py", line 59, in all
    result.append(ISCDhcpLdapConfig.get_by_ip(entry['attributes']['cn'][0]))
  File "/opt/marmoset/marmoset/dhcp/isc_dhcp_ldap_config.py", line 169, in get_by_ip
    return ISCDhcpLdapConfig.__get_dhcp_config(dn)
  File "/opt/marmoset/marmoset/dhcp/isc_dhcp_ldap_config.py", line 134, in __get_dhcp_config
    mac = re.search('(([0-9a-f]{2}:){5}[0-9a-f]{2})', mac_option).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

The issue is that the regex used to validate the MAC address does only accept lower case letters, this should be changed to match the regex used for validation while creating new entries.

**Comment by bastelfreak** [comment]
@heg-hpo this should be fixed now, could you please test again?

**Comment by ghost** [comment]
works for me.
